### PR TITLE
categoryPath not working

### PR DESCRIPTION
**Pull request by s-jakob**
The function isLeaf ist the wring way around. Its true if not a leaf and false if it is.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @s-jakob 
I think this is duplicated by https://github.com/shopwareLabs/SwagImportExport/pull/10

**Comment by t2oh4e** [comment]
@mitelg That's the 3rd PR to fix this issue... Perhaps it would be a good idea to accept my fix :p

**Comment by s-jakob** [comment]
ohh thanks. Please accept the fix. I don't want to hot-fix it every time. 
Btw. it would be a nice if you extend the documentation. Most customers are not aware of the feature to use category names.

**Comment by mitelg** [comment]
@t2oh4e 
yeah that's right. I will trigger some people again :blush:

**Pull request closed without merging**
