### PR TITLE
It fixes following problem: if any field has the value "0", this field…

### PR DESCRIPTION
**Pull request by waldicom**
… will be removed from array. There is no possibility to set a field to the value 0 (in my case it was an attribute, which should be set to 0 instead of 1)

### CODE REVIEW

**Comment by mitelg** [comment]
hey @waldicom 
thanks for your contribution! we already have a ticket where a similar problem is described
https://issues.shopware.com/#/issues/PT-4724

I will leave a comment with a hint to this PR. we must find a solution which fits all need. in some casess it is necessary to import a NULL value for example

**Comment by waldicom** [comment]
Hello Michael,

thank you for your answer. It lloks like this "bug" was introduced in  this commit: de585498daae4d4b51157492795fd0b958f08bba
So I thought that this is a regression bug (but I may be wrong)

**Comment by mitelg** [comment]
Hi @waldicom 
oh yeah, you are right! this is a regression. 

@SimonBaeumer could you please have look here?
https://github.com/shopwareLabs/SwagImportExport/commit/de585498daae4d4b51157492795fd0b958f08bba#diff-9a18181b27d4a48ae9f98ccf3ced5269R24

We have to fix this

**Comment by SimonBaeumer** [comment]
Hey @waldicom,

it would be nice if you could rename the method `prepareInitalData` to document the behaviour of this method. Further a regression test would be very nice for this behaviour.

Thank you very much for your contributing, you are completely right with your PR.

**Comment by waldicom** [comment]
Hello @SimonBaeumer ,

do you mean, I sholuld rename the method prepareInitialData() in all places in the plugin where this method is used? Yes, sure, I can do it.
And yes, with pleasure I would like to write a regression test for the "new" method.

**Comment by mitelg** [comment]
Hey @waldicom 
we merged your commit with d4ed9dfbd52f72002f192b80a08f823cd6bac4ab
thanks again! :+1:

**Pull request closed without merging**
