### PR TITLE
fix upload file override

### PR DESCRIPTION
**Pull request by Dominikrt**
### 1. Why is this change necessary?
File upload override uploaded files with same name.

### 2. What does this change do, exactly?
Check the uploaded file, if name already exists and add a random string to name to prevent override.

### 3. Describe each step to reproduce the issue or behaviour.
upload a file with the same name from an in or export. The old file in log will be override.

### CODE REVIEW

**Comment by rathmerdominik** [comment]
Hey there!

Thanks for your contribution @Dominikrt to Shopware with the pull request!

Is it maybe possible that instead of appending random strings to the filename, you rather take in seconds and milliseconds to the filename?

This will also ensure that no files will be overwritten and also causes more precise dates for the log 

Best regards from Schöppingen!

**Comment by Dominikrt** [comment]
Hi @rathmerdominik,

did you mean, add the Unix Timestamp and Millisecond's or a human readable timestamp with date, time and milliseconds?

Best regards

**Comment by Dominikrt** [comment]
Hi,
i switch't now to a similar schema like the export function.
`{filename}.{timestamp}-{randomstring}.{fileextension}`

Backup for the old commit can you find [here](https://github.com/Dominikrt/Shopware5-SwagImportExport/tree/upload-override-random)

**Comment by mitelg** [comment]
thanks for your contribution @Dominikrt  👍🎉💙

**Pull request closed without merging**
