### PR TITLE
Added article price filter

### PR DESCRIPTION
**Pull request by pascalheidman-bedarf**
I added the possibility to add filters to article price exports. Code is based on the normal article export.

### CODE REVIEW

**Comment by htkassner** [comment]
Hello Pascal. Thank you for your contribution. Can you please run the tests? 2 tests are actually failing. These need to be controlled and fixed to be merged.

**Comment by pascalheidman-bedarf** [comment]
@htkassner sadly I can't as `psh` takes more than 60 seconds on my machine which is the limit for running processes (default value for Symfony Process, psh doesn't set anything)

**Comment by mitelg** [comment]
@pascalheidman-bedarf did you try the local execution? psh without the docker commands?

**Comment by htkassner** [comment]
Fixed the tests. Should be merged soon. Thank you for your contribution!

**Comment by pascalheidman-bedarf** [comment]
@htkassner Thanks a lot for fixing testcases!
Still trying to get psh/[plugin-dev-tools](https://github.com/shopwareLabs/plugin-dev-tools) running on my mac so hopefully next contribution will be better tested ;)

**Comment by mitelg** [comment]
@pascalheidman-bedarf could be possible, that there is a problem. but as I'm not on Mac, I could not reproduce this issue :wink: 
if you find a fix, a PR would be nice :blush: https://github.com/shopwareLabs/plugin-dev-tools

**Pull request closed without merging**
